version: "3"

services:
  postgres-main:
    container_name: postgres-main
    image: postgres:alpine
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: main
    ports:
      - 5432:5432
